# Generated by Django 5.2.14 on 2026-05-08 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drills', '0001_initial'),
        ('ships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drillattendance',
            name='crew_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetydrill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetydrill',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_drills', to='ships.ship'),
        ),
        migrations.AddField(
            model_name='drillattendance',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='drills.safetydrill'),
        ),
        migrations.AlterUniqueTogether(
            name='drillattendance',
            unique_together={('drill', 'crew_member')},
        ),
    ]
