# Generated by Django 5.2.14 on 2026-05-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('vessel_type', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=100)),
                ('port_of_registry', models.CharField(max_length=200)),
                ('gross_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('docked', 'Docked'), ('maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ships',
                'ordering': ['name'],
            },
        ),
    ]
